import type { CourseCandidate } from "./recommendation";

/**
 * Temporary demo records used to validate UX and recommendation logic.
 * These are NOT production university facts and must be replaced with
 * verified CRICOS/university/government sourced records before launch.
 */
export const demoCourses: CourseCandidate[] = [
  {
    id: "demo-1",
    university: "Demo University Victoria",
    course: "Master of Cyber Security",
    qualificationLevel: "Master's degree",
    field: "Cyber Security",
    state: "VIC",
    city: "Ballarat",
    regional: true,
    annualFee: 32000,
    durationMonths: 24,
    estimatedMonthlyLiving: 1900,
    careerTags: ["Cyber Security Analyst", "ICT Security Specialist", "Security Engineer", "Cyber Security"],
    backgroundTags: ["Information Technology", "Computer Science", "Software Engineering", "Cyber Security"],
    migrationAlignment: "Strong",
    scholarshipNote: "Illustrative scholarship opportunity",
    verificationStatus: "DEMO",
  },
  {
    id: "demo-2",
    university: "Demo Metropolitan Institute",
    course: "Master of Information Technology",
    qualificationLevel: "Master's degree",
    field: "Information Technology",
    state: "VIC",
    city: "Melbourne",
    regional: false,
    annualFee: 39000,
    durationMonths: 24,
    estimatedMonthlyLiving: 2700,
    careerTags: ["Software Developer", "Systems Analyst", "ICT Consultant", "Software Engineer"],
    backgroundTags: ["Information Technology", "Computer Science", "Software Engineering", "Information Systems"],
    migrationAlignment: "Moderate",
    verificationStatus: "DEMO",
  },
  {
    id: "demo-3",
    university: "Demo South Australia University",
    course: "Master of Software Engineering",
    qualificationLevel: "Master's degree",
    field: "Software Engineering",
    state: "SA",
    city: "Adelaide",
    regional: true,
    annualFee: 35000,
    durationMonths: 24,
    estimatedMonthlyLiving: 2200,
    careerTags: ["Software Engineer", "Software Developer", "Application Developer", "DevOps Engineer"],
    backgroundTags: ["Software Engineering", "Computer Science", "Information Technology"],
    migrationAlignment: "Strong",
    verificationStatus: "DEMO",
  },
  {
    id: "demo-4",
    university: "Demo Queensland Technology University",
    course: "Master of Data Science",
    qualificationLevel: "Master's degree",
    field: "Data Science",
    state: "QLD",
    city: "Brisbane",
    regional: false,
    annualFee: 37000,
    durationMonths: 24,
    estimatedMonthlyLiving: 2450,
    careerTags: ["Data Scientist", "Data Analyst", "Machine Learning Engineer", "AI Engineer"],
    backgroundTags: ["Computer Science", "Information Technology", "Mathematics", "Statistics", "Data Science"],
    migrationAlignment: "Moderate",
    verificationStatus: "DEMO",
  },
  {
    id: "demo-5",
    university: "Demo Tasmania University",
    course: "Master of Information Systems",
    qualificationLevel: "Master's degree",
    field: "Information Systems",
    state: "TAS",
    city: "Hobart",
    regional: true,
    annualFee: 30000,
    durationMonths: 24,
    estimatedMonthlyLiving: 2000,
    careerTags: ["ICT Business Analyst", "Systems Analyst", "ICT Consultant", "Business Analyst"],
    backgroundTags: ["Information Technology", "Information Systems", "Business", "Computer Science"],
    migrationAlignment: "Moderate",
    verificationStatus: "DEMO",
  },
];
