import type { DemoCampus, DemoCourse, DemoSuburb, DemoUniversity, EvidenceRef, RouteOption } from "./types";

const demoEvidence = (note: string): EvidenceRef => ({
  sourceName: "UniPath Local Demo Fixture",
  publisher: "UniPath Australia",
  retrievedAt: "2026-08-19",
  lastVerifiedAt: "2026-08-19",
  status: "DEMO",
  note,
});

export const demoUniversities: DemoUniversity[] = [
  { id: "u-fed", name: "Demo Federation University", state: "VIC", reputationScore: 78 },
  { id: "u-metro-vic", name: "Demo Melbourne Technology University", state: "VIC", reputationScore: 90 },
  { id: "u-nsw", name: "Demo Sydney Digital University", state: "NSW", reputationScore: 91 },
  { id: "u-qld", name: "Demo Queensland Innovation University", state: "QLD", reputationScore: 84 },
  { id: "u-sa", name: "Demo South Australia University", state: "SA", reputationScore: 82 },
];

export const demoSuburbs: DemoSuburb[] = [
  {
    id: "s-ballarat",
    name: "Ballarat Central (Demo)",
    state: "VIC",
    weeklyRentCents: 26000,
    weeklyGroceriesCents: 12000,
    weeklyUtilitiesCents: 5500,
    weeklyPersonalCents: 7000,
    evidence: [demoEvidence("Illustrative local-development living costs only.")],
  },
  {
    id: "s-clayton",
    name: "Clayton (Demo)",
    state: "VIC",
    weeklyRentCents: 34000,
    weeklyGroceriesCents: 12500,
    weeklyUtilitiesCents: 6000,
    weeklyPersonalCents: 8000,
    evidence: [demoEvidence("Illustrative local-development living costs only.")],
  },
  {
    id: "s-parramatta",
    name: "Parramatta (Demo)",
    state: "NSW",
    weeklyRentCents: 41000,
    weeklyGroceriesCents: 13000,
    weeklyUtilitiesCents: 6500,
    weeklyPersonalCents: 8500,
    evidence: [demoEvidence("Illustrative local-development living costs only.")],
  },
  {
    id: "s-brisbane",
    name: "Brisbane South (Demo)",
    state: "QLD",
    weeklyRentCents: 35000,
    weeklyGroceriesCents: 12500,
    weeklyUtilitiesCents: 6000,
    weeklyPersonalCents: 8000,
    evidence: [demoEvidence("Illustrative local-development living costs only.")],
  },
  {
    id: "s-adelaide",
    name: "Adelaide CBD Fringe (Demo)",
    state: "SA",
    weeklyRentCents: 30000,
    weeklyGroceriesCents: 12000,
    weeklyUtilitiesCents: 5500,
    weeklyPersonalCents: 7500,
    evidence: [demoEvidence("Illustrative local-development living costs only.")],
  },
];

export const demoCampuses: DemoCampus[] = [
  { id: "c-ballarat", universityId: "u-fed", name: "Ballarat Campus (Demo)", suburbId: "s-ballarat", state: "VIC", regional: true },
  { id: "c-melbourne", universityId: "u-metro-vic", name: "Clayton Campus (Demo)", suburbId: "s-clayton", state: "VIC", regional: false },
  { id: "c-sydney", universityId: "u-nsw", name: "Parramatta Campus (Demo)", suburbId: "s-parramatta", state: "NSW", regional: false },
  { id: "c-brisbane", universityId: "u-qld", name: "Brisbane Campus (Demo)", suburbId: "s-brisbane", state: "QLD", regional: false },
  { id: "c-adelaide", universityId: "u-sa", name: "Adelaide Campus (Demo)", suburbId: "s-adelaide", state: "SA", regional: true },
];

export const demoCourses: DemoCourse[] = [
  {
    id: "course-se-fed",
    universityId: "u-fed",
    campusId: "c-ballarat",
    name: "Master of Software Engineering (Demo)",
    qualificationLevel: "Master",
    field: "Information Technology",
    annualTuitionCents: 3450000,
    durationYears: 2,
    occupations: ["Software Engineer", "Software Developer"],
    skillTags: ["software", "web", "programming", "databases"],
    scholarshipPercent: 10,
    labourMarketScore: 84,
    migrationAlignmentScore: 82,
    evidence: [demoEvidence("Course, fee, career and migration values are sample data only.")],
  },
  {
    id: "course-it-vic",
    universityId: "u-metro-vic",
    campusId: "c-melbourne",
    name: "Master of Information Technology (Demo)",
    qualificationLevel: "Master",
    field: "Information Technology",
    annualTuitionCents: 4100000,
    durationYears: 2,
    occupations: ["ICT Business Analyst", "Software Developer", "Systems Analyst"],
    skillTags: ["software", "business analysis", "databases", "cloud"],
    scholarshipPercent: 8,
    labourMarketScore: 92,
    migrationAlignmentScore: 70,
    evidence: [demoEvidence("Course, fee, career and migration values are sample data only.")],
  },
  {
    id: "course-cs-nsw",
    universityId: "u-nsw",
    campusId: "c-sydney",
    name: "Master of Computer Science (Demo)",
    qualificationLevel: "Master",
    field: "Information Technology",
    annualTuitionCents: 4550000,
    durationYears: 2,
    occupations: ["Software Engineer", "Data Scientist"],
    skillTags: ["algorithms", "software", "ai", "data"],
    labourMarketScore: 94,
    migrationAlignmentScore: 72,
    evidence: [demoEvidence("Course, fee, career and migration values are sample data only.")],
  },
  {
    id: "course-cyber-qld",
    universityId: "u-qld",
    campusId: "c-brisbane",
    name: "Master of Cyber Security (Demo)",
    qualificationLevel: "Master",
    field: "Information Technology",
    annualTuitionCents: 3900000,
    durationYears: 2,
    occupations: ["Cyber Security Analyst", "ICT Security Specialist"],
    skillTags: ["security", "networking", "cloud", "linux"],
    scholarshipPercent: 5,
    labourMarketScore: 89,
    migrationAlignmentScore: 77,
    evidence: [demoEvidence("Course, fee, career and migration values are sample data only.")],
  },
  {
    id: "course-se-sa",
    universityId: "u-sa",
    campusId: "c-adelaide",
    name: "Master of Software Engineering (Demo SA)",
    qualificationLevel: "Master",
    field: "Information Technology",
    annualTuitionCents: 3600000,
    durationYears: 2,
    occupations: ["Software Engineer", "Developer Programmer"],
    skillTags: ["software", "programming", "devops", "cloud"],
    scholarshipPercent: 12,
    labourMarketScore: 81,
    migrationAlignmentScore: 88,
    evidence: [demoEvidence("Course, fee, career and migration values are sample data only.")],
  },
  {
    id: "course-data-vic",
    universityId: "u-metro-vic",
    campusId: "c-melbourne",
    name: "Master of Data Science (Demo)",
    qualificationLevel: "Master",
    field: "Information Technology",
    annualTuitionCents: 4250000,
    durationYears: 2,
    occupations: ["Data Scientist", "Data Analyst"],
    skillTags: ["python", "data", "statistics", "ai"],
    scholarshipPercent: 8,
    labourMarketScore: 90,
    migrationAlignmentScore: 66,
    evidence: [demoEvidence("Course, fee, career and migration values are sample data only.")],
  },
];

export const demoRouteFixtures: Record<string, RouteOption[]> = {
  "s-ballarat:c-ballarat": [
    { id: "r1", mode: "driving", durationMinutes: 12, distanceKm: 7.4, transfers: 0, walkingMinutes: 0, summary: "Drive directly to campus (demo)." },
    { id: "r2", mode: "public_transport", durationMinutes: 31, distanceKm: 8.2, transfers: 1, walkingMinutes: 8, summary: "Walk + local bus + walk (demo)." },
  ],
  "s-clayton:c-melbourne": [
    { id: "r3", mode: "driving", durationMinutes: 14, distanceKm: 8.8, transfers: 0, walkingMinutes: 0, summary: "Drive directly to campus (demo)." },
    { id: "r4", mode: "public_transport", durationMinutes: 28, distanceKm: 9.6, transfers: 1, walkingMinutes: 7, summary: "Bus + walk (demo)." },
  ],
  "s-adelaide:c-adelaide": [
    { id: "r5", mode: "driving", durationMinutes: 15, distanceKm: 9.1, transfers: 0, walkingMinutes: 0, summary: "Drive directly to campus (demo)." },
    { id: "r6", mode: "public_transport", durationMinutes: 27, distanceKm: 10.4, transfers: 1, walkingMinutes: 6, summary: "Bus/tram + walk (demo)." },
  ],
};
